//! Code generator — SPEC-002 Tier 1 lowering and async shell generation
//!
//! Consumes a `ClassificationResult` and emits Rust source code.
//! Phase 2b will expand this to a full line-for-line AST lowering pass.
//! This module currently handles:
//!
//! - Tier 1 struct and enum stubs with `#[derive(uniffi::Record)]`
//! - Tier 2 class stubs with `Arc<Mutex<T>>` and `uniffi::Object`
//! - Function signatures from the type mapping table
//! - Async callback scaffolding (Tier A1 / A1-sync) — SPEC-006 §3
//! - SPEC-004 UniFFI annotations

use anyhow::{bail, Result};
use std::str::FromStr;

use crate::classify::{AsyncTier, ClassificationResult, DeclarationResult, SyncTier};

// ── Async mode ────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AsyncMode {
    /// Three-zone hybrid: callback bridge + generated Swift continuation wrapper.
    Bridge,
    /// Native UniFFI async (Stage 2 — gated on ADR-006 review trigger).
    Native,
}

impl FromStr for AsyncMode {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "bridge" => Ok(AsyncMode::Bridge),
            "native" => Ok(AsyncMode::Native),
            other    => Err(format!("unknown async mode: {other}")),
        }
    }
}

impl clap::ValueEnum for AsyncMode {
    fn value_variants<'a>() -> &'a [Self] {
        &[AsyncMode::Bridge, AsyncMode::Native]
    }
    fn to_possible_value(&self) -> Option<clap::builder::PossibleValue> {
        Some(match self {
            AsyncMode::Bridge => clap::builder::PossibleValue::new("bridge"),
            AsyncMode::Native => clap::builder::PossibleValue::new("native"),
        })
    }
}

// ── Public entry points ───────────────────────────────────────────────────────

/// Lower Tier 1 declarations only (no async, no class).
pub fn lower_tier1(result: &ClassificationResult) -> Result<String> {
    transpile(result, AsyncMode::Bridge)
}

/// Full transpile: all tiers, with chosen async mode.
pub fn transpile(result: &ClassificationResult, async_mode: AsyncMode) -> Result<String> {
    let mut out = preamble(&result.file);

    for decl in &result.declarations {
        match decl.tier {
            SyncTier::Tier1 => {
                out.push_str(&emit_tier1(decl, async_mode));
            }
            SyncTier::Tier2 => {
                out.push_str(&emit_tier2(decl, async_mode));
            }
            SyncTier::Tier3 => {
                // Tier 3 declarations are Shell-only; emit a comment stub.
                out.push_str(&format!(
                    "// TIER-3 SKIP: `{}` ({}) is Shell-only — see T3 diagnostics.\n\n",
                    decl.name, decl.kind
                ));
            }
        }
    }

    Ok(out)
}

// ── Preamble ──────────────────────────────────────────────────────────────────

fn preamble(source_file: &str) -> String {
    format!(
        "// Generated by sarah-cli — DO NOT EDIT\n\
         // Source: {source_file}\n\
         // Phase 2 output — Tier 1 / Tier 2 lowering\n\
         //\n\
         // Async mode: three-zone hybrid (SPEC-006)\n\
         // See: SPEC-002, SPEC-003, SPEC-004, SPEC-006\n\n\
         use std::sync::{{Arc, Mutex}};\n\n"
    )
}

// ── Tier 1 emitter ────────────────────────────────────────────────────────────

fn emit_tier1(decl: &DeclarationResult, async_mode: AsyncMode) -> String {
    match decl.kind.as_str() {
        "struct" => emit_struct(decl),
        "enum"   => emit_enum(decl),
        "func"   => emit_func(decl, async_mode, false),
        _        => format!("// UNSUPPORTED TIER-1 KIND: {}\n\n", decl.kind),
    }
}

fn emit_struct(decl: &DeclarationResult) -> String {
    format!(
        "/// Transpiled from Swift `struct {name}`\n\
         /// TIER-1: value type — SPEC-002\n\
         #[derive(Debug, Clone, uniffi::Record)]\n\
         pub struct {name} {{\n\
         \t// TODO: add fields (Phase 2b AST parser)\n\
         }}\n\n",
        name = decl.name
    )
}

fn emit_enum(decl: &DeclarationResult) -> String {
    format!(
        "/// Transpiled from Swift `enum {name}`\n\
         /// TIER-1: value type — SPEC-002\n\
         #[derive(Debug, Clone, uniffi::Enum)]\n\
         pub enum {name} {{\n\
         \t// TODO: add variants (Phase 2b AST parser)\n\
         }}\n\n",
        name = decl.name
    )
}

fn emit_func(decl: &DeclarationResult, async_mode: AsyncMode, _is_method: bool) -> String {
    match &decl.async_tier {
        None => emit_sync_func(decl),
        Some(AsyncTier::A1) | Some(AsyncTier::A1Sync) => {
            emit_async_func(decl, async_mode)
        }
        Some(AsyncTier::A2) => emit_async_func_a2(decl, async_mode),
    }
}

fn emit_sync_func(decl: &DeclarationResult) -> String {
    format!(
        "/// Transpiled from Swift `func {name}`\n\
         /// TIER-1: sync function — SPEC-002\n\
         #[uniffi::export]\n\
         pub fn {name}() {{\n\
         \ttodo!(\"Phase 2b: implement {name}\")\n\
         }}\n\n",
        name = decl.name
    )
}

fn emit_async_func(decl: &DeclarationResult, async_mode: AsyncMode) -> String {
    let tier_label = match &decl.async_tier {
        Some(AsyncTier::A1Sync) => "A1-sync — spawn_blocking",
        _ =>                       "A1 — Tokio spawn + callback",
    };
    match async_mode {
        AsyncMode::Bridge => format!(
            "/// Transpiled from Swift `async func {name}`\n\
             /// TIER-{tier}: three-zone hybrid bridge (SPEC-006 §3)\n\
             ///\n\
             /// The Swift Shell wraps this with `withCheckedThrowingContinuation`.\n\
             /// Rust side fires the callback when work completes.\n\
             #[uniffi::export(callback_interface)]\n\
             pub trait {name}Callback: Send + Sync {{\n\
             \tfn on_result(&self, result: ());  // TODO: typed result (Phase 2b)\n\
             \tfn on_error(&self, error: String);\n\
             }}\n\n\
             #[uniffi::export]\n\
             pub fn {name}(callback: Arc<dyn {name}Callback>) {{\n\
             \ttokio::spawn(async move {{\n\
             \t\t// TODO: implement {name} (Phase 2b)\n\
             \t\tcallback.on_result(());\n\
             \t}});\n\
             }}\n\n",
            name = decl.name,
            tier = tier_label,
        ),
        AsyncMode::Native => format!(
            "/// Transpiled from Swift `async func {name}`\n\
             /// TIER-A1: native UniFFI async — Stage 2 (ADR-006)\n\
             /// NOTE: ensure UniFFI Sendable gap is resolved before use.\n\
             #[uniffi::export]\n\
             pub async fn {name}() {{\n\
             \ttodo!(\"Phase 2b: implement {name}\")\n\
             }}\n\n",
            name = decl.name,
        ),
    }
}

fn emit_async_func_a2(decl: &DeclarationResult, async_mode: AsyncMode) -> String {
    let mut out = format!(
        "/// Transpiled from Swift `async func {name}` on class receiver\n\
         /// TIER-2/A2: ASYNC-LOCK-RISK mitigated — lock-before-await pattern (SPEC-006 §4)\n\
         ///\n\
         /// Acquire the Mutex, clone required state, drop the lock, then await.\n\
         /// Never hold a MutexGuard across an await point.\n",
        name = decl.name
    );
    out.push_str(&emit_async_func(decl, async_mode));
    out
}

// ── Tier 2 emitter ────────────────────────────────────────────────────────────

fn emit_tier2(decl: &DeclarationResult, async_mode: AsyncMode) -> String {
    match decl.kind.as_str() {
        "class" => emit_class(decl),
        "func"  => emit_func(decl, async_mode, true),
        _       => format!("// UNSUPPORTED TIER-2 KIND: {}\n\n", decl.kind),
    }
}

fn emit_class(decl: &DeclarationResult) -> String {
    format!(
        "/// Transpiled from Swift `class {name}`\n\
         /// TIER-2: shared ownership — Arc<Mutex<T>> (SPEC-003)\n\
         #[derive(uniffi::Object)]\n\
         pub struct {name} {{\n\
         \tinner: Mutex<{name}Inner>,\n\
         }}\n\n\
         struct {name}Inner {{\n\
         \t// TODO: add fields (Phase 2b AST parser)\n\
         }}\n\n\
         #[uniffi::export]\n\
         impl {name} {{\n\
         \t#[uniffi::constructor]\n\
         \tpub fn new() -> Arc<Self> {{\n\
         \t\tArc::new(Self {{ inner: Mutex::new({name}Inner {{}}) }})\n\
         \t}}\n\
         }}\n\n",
        name = decl.name
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::classify::classify_file;
    use std::path::PathBuf;

    fn path() -> PathBuf { PathBuf::from("test.swift") }

    #[test]
    fn struct_emits_uniffi_record() {
        let src = "struct Point {}";
        let r = classify_file(&path(), src);
        let out = transpile(&r, AsyncMode::Bridge).unwrap();
        assert!(out.contains("#[derive(Debug, Clone, uniffi::Record)]"));
        assert!(out.contains("pub struct Point"));
    }

    #[test]
    fn class_emits_arc_mutex() {
        let src = "class SessionManager {}";
        let r = classify_file(&path(), src);
        let out = transpile(&r, AsyncMode::Bridge).unwrap();
        assert!(out.contains("Arc::new"));
        assert!(out.contains("Mutex::new"));
        assert!(out.contains("#[derive(uniffi::Object)]"));
    }

    #[test]
    fn async_func_bridge_emits_callback_trait() {
        let src = "struct Svc {}\nasync func loadData() async {}";
        let r = classify_file(&path(), src);
        let out = transpile(&r, AsyncMode::Bridge).unwrap();
        assert!(out.contains("callback_interface"));
        assert!(out.contains("tokio::spawn"));
    }

    #[test]
    fn tier3_emits_skip_comment() {
        let src = "protocol Repo { associatedtype Item }";
        let r = classify_file(&path(), src);
        let out = transpile(&r, AsyncMode::Bridge).unwrap();
        assert!(out.contains("TIER-3 SKIP"));
    }
}
