//! Swift Shell emitter — Phase 2c
//!
//! Generates the SwiftUI-facing `.swift` source file that:
//!
//! 1. Imports the UniFFI-generated bindings (`import CoreFFI`).
//! 2. Wraps every async Rust function with `withCheckedThrowingContinuation`
//!    (Strategy A from SPEC-006).
//! 3. Wraps every sync Rust function with a thin Swift forwarding call.
//! 4. Wraps every `uniffi::Object` (class) with an `ObservableObject`
//!    `@Published` ViewModel (SPEC-003).
//! 5. Emits a `SarahError` bridging type used by all generated async wrappers.
//!
//! The output is a complete, compilable `.swift` file ready to drop into
//! the `shell/` package.

use crate::parser::{SwiftClass, SwiftEnum, SwiftFile, SwiftFunc, SwiftStruct};
use crate::types::parse_type;

// ── Entry point ───────────────────────────────────────────────────────────────

/// Generate the full Swift Shell source for a parsed `SwiftFile`.
pub fn emit_shell(ir: &SwiftFile, module_name: &str) -> String {
    let mut out = shell_preamble(module_name);

    // SarahError bridging type (emitted once per file)
    out.push_str(SARAH_ERROR_TYPE);

    // Sync struct forwarding typealias stubs
    for s in &ir.structs {
        out.push_str(&emit_struct_alias(s));
    }

    // Enum forwarding typealiases
    for e in &ir.enums {
        out.push_str(&emit_enum_alias(e));
    }

    // ObservableObject ViewModels for each class
    for c in &ir.classes {
        out.push_str(&emit_class_viewmodel(c));
    }

    // Async wrapper functions for top-level funcs
    for f in &ir.funcs {
        if f.is_async {
            out.push_str(&emit_async_wrapper(f));
        } else {
            out.push_str(&emit_sync_wrapper(f));
        }
    }

    out
}

// ── Preamble ──────────────────────────────────────────────────────────────────

fn shell_preamble(module_name: &str) -> String {
    format!(
        "// Generated by sarah-cli — DO NOT EDIT\n\
         // Phase 2c Swift Shell output\n\
         // See: SPEC-003 (classes), SPEC-004 (UniFFI), SPEC-006 (async)\n\n\
         import SwiftUI\n\
         import {module_name}\n\n"
    )
}

const SARAH_ERROR_TYPE: &str = r#"// ── Error bridging ──────────────────────────────────────────────────────────

/// Bridges Rust errors (String-serialised by UniFFI) into Swift's error system.
public struct SarahError: LocalizedError {
    public let message: String
    public init(_ message: String) { self.message = message }
    public var errorDescription: String? { message }
}

"#;

// ── Struct / Enum aliases ─────────────────────────────────────────────────────
//
// UniFFI generates the real Swift struct type in the generated bindings.
// The Shell just re-exports it so ViewModel code can refer to it without
// importing CoreFFI directly.

fn emit_struct_alias(s: &SwiftStruct) -> String {
    format!(
        "/// Shell re-export: `{name}` is generated by UniFFI from the Rust Core.\n\
         public typealias {name} = CoreFFI.{name}\n\n",
        name = s.name
    )
}

fn emit_enum_alias(e: &SwiftEnum) -> String {
    format!(
        "/// Shell re-export: `{name}` is generated by UniFFI from the Rust Core.\n\
         public typealias {name} = CoreFFI.{name}\n\n",
        name = e.name
    )
}

// ── ObservableObject ViewModel for classes ────────────────────────────────────

fn emit_class_viewmodel(c: &SwiftClass) -> String {
    // @Published properties from the class fields
    let published: String = c.fields.iter().map(|f| {
        let swift_type = if f.optional {
            format!("{}?", f.swift_type)
        } else {
            f.swift_type.clone()
        };
        let default_val = default_for_swift_type(&f.swift_type, f.optional);
        format!("    @Published public var {}: {} = {}\n",
            f.name, swift_type, default_val)
    }).collect();

    // Method forwarding stubs
    let method_stubs: String = c.methods.iter().map(|m| {
        if m.is_async {
            emit_async_task_wrapper(m, &c.name)
        } else {
            emit_viewmodel_sync_method(m, &c.name)
        }
    }).collect();

    format!(
        "/// Generated ViewModel for Swift `class {name}` (SPEC-003)\n\
         @MainActor\n\
         public final class {name}ViewModel: ObservableObject {{\n\
         {published}\
         \n    private let core: CoreFFI.{name}\n\
         \n    public init() {{ self.core = CoreFFI.{name}.init() }}\n\
         \n{method_stubs}}}\
         \n\n",
        name   = c.name,
        published = if published.is_empty() { "    // (no fields)\n".to_owned() } else { published },
    )
}

fn emit_async_task_wrapper(f: &SwiftFunc, class_name: &str) -> String {
    let params = swift_param_list(f);
    let args   = swift_call_args(f);
    let ret_type = if f.return_type == "Void" || f.return_type.is_empty() {
        String::new()
    } else {
        format!(" -> {}", f.return_type)
    };
    let throws = if f.is_throws { " throws" } else { "" };

    format!(
        "    /// Async wrapper for `{class_name}.{name}` (SPEC-006 Strategy A)\n\
         \t@discardableResult\n\
         \tpublic func {name}({params}) async{throws}{ret_type} {{\n\
         \t\ttry await withCheckedThrowingContinuation {{ (continuation: CheckedContinuation<Void, Error>) in\n\
         \t\t\tlet cb = {name_cap}Callback(\n\
         \t\t\t\tonResult: {{ continuation.resume() }},\n\
         \t\t\t\tonError:  {{ err in continuation.resume(throwing: SarahError(err)) }}\n\
         \t\t\t)\n\
         \t\t\tcore.{name}({args}callback: cb)\n\
         \t\t}}\n\
         \t}}\n\n",
        name     = f.name,
        name_cap = capitalise(&f.name),
        class_name = class_name,
        params = params,
        args   = if args.is_empty() { String::new() } else { format!("{args}, ") },
        throws = throws,
        ret_type = ret_type,
    )
}

fn emit_viewmodel_sync_method(f: &SwiftFunc, class_name: &str) -> String {
    let params   = swift_param_list(f);
    let args     = swift_call_args(f);
    let ret_type = if f.return_type == "Void" || f.return_type.is_empty() {
        String::new()
    } else {
        format!(" -> {}", f.return_type)
    };
    format!(
        "\tpublic func {name}({params}){ret_type} {{\n\
         \t\tcore.{name}({args})\n\
         \t}}\n\n",
        name = f.name,
    )
}

// ── Top-level function wrappers ───────────────────────────────────────────────

fn emit_async_wrapper(f: &SwiftFunc) -> String {
    let params   = swift_param_list(f);
    let args     = swift_call_args(f);
    let ret_type = if f.return_type == "Void" || f.return_type.is_empty() {
        "Void".to_owned()
    } else {
        f.return_type.clone()
    };
    let cont_type = if ret_type == "Void" { "Void".to_owned() } else { ret_type.clone() };

    format!(
        "/// Async Shell wrapper for `{name}` (SPEC-006 Strategy A)\n\
         public func {name}({params}) async throws -> {ret_type} {{\n\
         \treturn try await withCheckedThrowingContinuation {{ (continuation: CheckedContinuation<{cont_type}, Error>) in\n\
         \t\tlet cb = {name_cap}Callback(\n\
         \t\t\tonResult: {{ result in continuation.resume(returning: result) }},\n\
         \t\t\tonError:  {{ err    in continuation.resume(throwing: SarahError(err)) }},\n\
         \t\t\tonCancel: {{         continuation.resume(throwing: CancellationError()) }}\n\
         \t\t)\n\
         \t\tCoreFFI.{name}({args}callback: cb)\n\
         \t}}\n\
         }}\n\n",
        name     = f.name,
        name_cap = capitalise(&f.name),
    )
}

fn emit_sync_wrapper(f: &SwiftFunc) -> String {
    let params = swift_param_list(f);
    let args   = swift_call_args(f);
    let ret    = if f.return_type == "Void" || f.return_type.is_empty() {
        String::new()
    } else {
        format!(" -> {}", f.return_type)
    };
    format!(
        "/// Shell forwarding for `{name}` (sync)\n\
         public func {name}({params}){ret} {{\n\
         \treturn CoreFFI.{name}({args})\n\
         }}\n\n",
        name = f.name,
    )
}

// ── Parameter helpers ─────────────────────────────────────────────────────────

fn swift_param_list(f: &SwiftFunc) -> String {
    f.params.iter().map(|p| {
        let label = p.label.as_deref().unwrap_or(&p.name);
        let type_str = if p.optional {
            format!("{}?", p.swift_type)
        } else {
            p.swift_type.clone()
        };
        format!("{label} {}: {type_str}", p.name)
    }).collect::<Vec<_>>().join(", ")
}

fn swift_call_args(f: &SwiftFunc) -> String {
    f.params.iter().map(|p| {
        let label = p.label.as_deref().unwrap_or(&p.name);
        format!("{label}: {}", p.name)
    }).collect::<Vec<_>>().join(", ")
}

fn default_for_swift_type(swift_type: &str, optional: bool) -> &'static str {
    if optional { return "nil"; }
    match swift_type {
        "String"  => "\"\"",
        "Bool"    => "false",
        "Int" | "Int8" | "Int16" | "Int32" | "Int64"
        | "UInt" | "UInt8" | "UInt16" | "UInt32" | "UInt64" => "0",
        "Float" | "Double" | "CGFloat" | "TimeInterval" => "0.0",
        _ => "/* default */",  // caller must handle user-defined types
    }
}

fn capitalise(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None    => String::new(),
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::{parse, SwiftField};

    #[test]
    fn shell_contains_sarah_error_type() {
        let ir  = parse("");
        let out = emit_shell(&ir, "CoreFFI");
        assert!(out.contains("struct SarahError"));
        assert!(out.contains("LocalizedError"));
    }

    #[test]
    fn struct_generates_typealias() {
        let src = "struct Point { var x: Double; var y: Double }";
        let ir  = parse(src);
        let out = emit_shell(&ir, "CoreFFI");
        assert!(out.contains("typealias Point = CoreFFI.Point"));
    }

    #[test]
    fn class_generates_observable_object() {
        let src = r#"class Counter {
    var count: Int
    func increment() {}
}"#;
        let ir  = parse(src);
        let out = emit_shell(&ir, "CoreFFI");
        assert!(out.contains("ObservableObject"));
        assert!(out.contains("@Published"));
        assert!(out.contains("@MainActor"));
        assert!(out.contains("CounterViewModel"));
    }

    #[test]
    fn async_func_generates_continuation_wrapper() {
        let src = "async func fetchData() {}";
        let ir  = parse(src);
        let out = emit_shell(&ir, "CoreFFI");
        assert!(out.contains("withCheckedThrowingContinuation"));
        assert!(out.contains("SarahError"));
        assert!(out.contains("CancellationError"));
    }

    #[test]
    fn sync_func_generates_forwarding_call() {
        let src = "func add(lhs: Int, rhs: Int) -> Int { lhs + rhs }";
        let ir  = parse(src);
        let out = emit_shell(&ir, "CoreFFI");
        assert!(out.contains("public func add("));
        assert!(out.contains("CoreFFI.add("));
    }
}
